friend=['胡昊钧','王笑一','黄正一','刘伯僮','徐江平','勒晋嘉']
print(friend)
print(friend[0]+'是我损友。')
print(friend[1]+'也是我损友。')
print(friend[2]+'是我朋友。')
print(friend[3]+'也是我朋友。')
print(friend[4]+'还是我朋友。')
print(friend[5]+'是个傻逼(朋友)。')
friend2={'胡昊钧':'损友','王笑一':'损友','黄正一':'朋友','刘伯僮':'朋友','徐江平':'朋友','勒晋嘉':'傻逼'}
print(friend2)